on:
  schedule:
    - cron: '40 10 * * *'

jobs:
  actualizar-fecha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Obtener fecha y hora
      id: obtener-fecha
      run: echo "::set-output name=fecha::$(date +'%Y-%m-%d %H:%M:%S %Z')"

    - name: Actualizar fichero de fecha
      run: echo "${{ steps.obtener-fecha.outputs.fecha }}" > fecha
      
    - name: GIT commit and push docs
      env: 
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Continuous Integration
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git add docs
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
