name: Actualizar Fecha en Fichero
# Jorge del Cid Moreno
on:
  schedule:
    - cron: '40 10 * * *'

jobs:
  actualizar-fecha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Obtener fecha y hora
      id: obtener-fecha
      run: echo "::set-output name=fecha::$(date +'%Y-%m-%d %H:%M:%S %Z')"

    - name: Actualizar fichero de fecha
      run: echo "${{ steps.obtener-fecha.outputs.fecha }}" > fecha

    - name: Confirmar y enviar cambios
      run: |
        git add fecha
        git commit -m "Actualización de fecha y hora: ${{ steps.obtener-fecha.outputs.fecha }}"
        git remote remove origin
        git remote add origin https://Alpargato45:${{ secrets.TOKEN_GITHUB }}@github.com/Alpargato45/AlwaysContribution.git
        git push
