on:
  schedule:
    - cron: '40 10 * * *'

jobs:
  actualizar-fecha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Obtener fecha y hora
      id: obtener-fecha
      run: echo "::set-output name=fecha::$(date +'%Y-%m-%d %H:%M:%S %Z')"

    - name: Actualizar fichero de fecha
      run: echo "${{ steps.obtener-fecha.outputs.fecha }}" > fecha

  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_GITHUB }}

    # Build steps
    - uses: actions/setup-node@v3
      with:
        node-version: '12' 
    - name: Node Install
      run: npm ci
    - name: Node Build (fecha)
      run: npm run package

    # Commit and push all changed files. 
    # Must only affect files that are listed in "paths-ignore".
    - name: GIT Commit Build Artifacts (fecha)
      # Only run on main branch push (e.g. pull request merge).
      if: github.event_name == 'push'
      run: |
        git add fecha
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
