on:
  schedule:
    - cron: '40 10 * * *'

jobs:
  actualizar-fecha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/setup-node@v4

    - name: Configurar Git
      run: gh auth login --with-token ${{ secrets.TOKEN_GITHUB }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Obtener fecha y hora
      id: obtener-fecha
      run: echo "::set-output name=fecha::$(date +'%Y-%m-%d %H:%M:%S %Z')"

    - name: Actualizar fichero de fecha
      run: echo "${{ steps.obtener-fecha.outputs.fecha }}" > fecha

    - name: Confirmar y enviar cambios
      run: |
        git add fecha
        git commit -m "Actualización de fecha y hora: ${{ steps.obtener-fecha.outputs.fecha }}"
        git push

